repos:
- repo: local
  hooks:
    - id: check-copyright-notice
      name: check-copyright-notice
      description: Check copyright notice
      entry: python3 scripts/check_copyright_notice.py
      language: system
      types_or: [go]
