name: markdown
on:
  pull_request:
    paths:
      - '.github/workflows/markdown.yml'
      - '.github/markdownlint.json'
      - '.github/markdownlint.jsonc'
      - '**/*.md'

# Declare default permissions as read only.
permissions: read-all

jobs:
  markdown-check:
    uses: Open-CMSIS-Pack/workflows-and-actions-collection/.github/workflows/markdown-lint.yml@v1.0.0
    with:
      lint-config: '.github/markdownlint.jsonc'
      link-check-config: '.github/markdown-link-check.jsonc'
      ignore-files: 'third_party_licenses.md'
